# Sets up base image
FROM node:alpine

# Sets working directory inside the container to the app dir
#  where all of our project files reside
WORKDIR /app

# Copies package.json files from project into the containers working dir
COPY package*.json ./

# Install the dependencies inside the container
RUN npm install

# Copies the rest of the project files into the container
COPY . .

# Exposes port 5173
EXPOSE 5173

# Specifies the default command when the container starts
CMD ["npm", "run", "dev"]